backend:
  name: github
  repo: joaomaranhao/blog
  branch: main
publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
collections:
  - name: "articles"
    label: "Articles"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
